language: objective-c
osx_image: xcode7.2
xcode_project: Demo/Demo.xcodeproj
xcode_scheme: Demo
script:
- xcodebuild -workspace IntegratedSDK.xcworkspace -scheme Demo -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
env:
  global:
    secure: P6qAlVD2hNj6Wpeu1/EgRvXyIiOA0R2Gezguq1SAaQrM0nHeXwzYXm36z25HSN98zLkWZaYo/uHva8qFrE++3e8ERINmL4e1knX/CJWiAnWFhc9ak8q65//OOX96NgEBeQV5DH2K0KAcVIkKegYKOqU7UNZd1Zq66gmjYRQN5SkcluxDgwfXpDh0bdLxqNO+f1NRf91Iw2CWkq4GbqMMtLQ+63EpJSpyFsdXDBY4m2kJWJG53xygJ3TEXugZjcybYxjPLbJq57n2Ai7ecMB9CjpIcRCw47HBwxm1s5O4uM8JqEDJPwg9pFoNrTUj8Prc9xdj1HsedINLOa6Trnet0Tzr7uAIZi9d1IGdSzrkjy7KuqVvn/X1pAdcffWaqvi6Kt/exyKAPTWNb5pjGRsTGVjOErwlD4O85xfsh4qZe/+9PiYbj/PzS87q4UtVTYJfgBPNrAWPLfol2SsDVWPBru5N2ZCgdFfZNFBQK4mjWNv4+QO+3WJdmnpSUu0MEDGQX4WGtMULKilkXDsGNwq5Nly45CCw22liRvHk7TDLwBXInns+pa7FyJnW/y3TJ0CzItf1H0iL/6jeHnzVXNRb2rGEG8LNgvIvH8lMqInjljDYGlswAPsy8fVucwHpZLdHxdeQ5srv7im9xexXfP1mfQWi1hfEf/fhHPO9vnOgzyE=
