language: objective-c
osx_image: xcode8.2
xcode_project: Demo/Demo.xcodeproj
xcode_scheme: Demo
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/ForSDKTest.mobileprovision.enc -d -a -out scripts/profile/ForSDKTest.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild -workspace IntegratedSDK.xcworkspace -scheme Demo -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
env:
  global:
  - PROFILE_NAME="ForSDKTest"
  - secure: GuqIkgvwuxke3qt1BJdKtLeu7QgNi3j7ssBlFNdo5htUIB6mlWulzPJ0R+w6gJ0SZaBkrJ8JexaLPu3DpswD6t4im32ZjVSEO4GYph5B1U1TcPQVgz8z68ibzy++8ajQXJenNGsgep8IZoIYl/Vjj9iqfPasIp+eJdnuuAdesb3N4M2ULXIRBr4AINZHTofnPk6h56fq12bPjBwYqBvaNTPjVYfbSYZKhLtWzF2yzGqpn/8d+XFTHh3MVXbnrtVxwGdMsXCYSUDhAHEkcRAAIzZt8nPx8Ifoyq99sO910T3ehPGhm4bqXphuHie6atu9Dyua8SWeoERts7uL74zHZmieLMRw5Pc80KmW7gfzejJCYHUn1cNQztxpPEYXPohsv8p5+OhagkCLS+FBjpwq9/WkhmZAuEigA/YNMCItT0yMRL2TSTfXT/UM5GLnqlj3C2knJyPmFwHGf8DJtkUzuVfjSVV8G+cg3ZtMuB5a/XhNyA3lNcdVbbejoM9nNfZzQo4jHsbhcCFi7QFbtzVrxFU0PEoD4hUs85uuCKXNP/THvwSC3dmVoBlunO7qJXq97G/8Gdvo0nFhRgzegXb+W2JkAyzf5SZjGhJBxytMcVE65GHEKjh5dxIQEpomnGlYpKUKSir5jdepPjWs87nwIh9+VK+cMn15ElnF3c0EdFg=
  - secure: Ie7+k+cjwWzl6OXGgIKcCs0rpunhQf8yIJHHXeJfhFa+aLVD2fkHAi/YyBFz8HIdHycPj5gp4RBydnzHuFO8HP2HykgFfd3byrNcYm28XRHUaPgWTO4DsBNZoutAo/vSWe5S5Iem029Sp95gurO1xOqqIYILOrcG8X5FXpmc+VIXNUVH4Ogzh/VTvQ0SCTAYFW+Z0DhfTyEa/qulfag19NUa6jK2KScjE8GZKaHx65Y/Bg51ES6NRs1WBg7C6StA7/MVtqRpFo+AqfKjBynWblPBNCNgUuL9yi1XnA+naFcI165vjVjNInNuOjIJ0gz25GIzBwB07tUbxcEJ1Hj3VH+dG+5kpXwHSzJnOLFAIW9YHFRs3iv8+N1x8M1gdGLroK8y9nRQZXa95Ef0P4mWwfB3AR7bKp2e2SKUyOwk+3C0gAV2/+DfQDR/HtIcyVydXK8WOM1SSabGDBcEzcvVFRIDBZ1eBFDa3dXpGYeZ4TdFthMZ1qziJ/K4NGcaFde9bM2XrHK3FW+VCfkGdVEpmIOkENUxVOVG0o3W3+xKFbAx2UMKHmx+XXEIVFm25HUwN82cFy2cBl19sD2BOvHHoQHNn5sTx4+qIVfhqwW3Hw1P3iGo8JQuTNIYorEmtWmwIwLf9bfYroGjZzk+Cs0BITa3hRC952M3M7NJA+onacI=
